---
- include: install_and_configure.yml
- include: hooks.yml
- include: redirector_service.yml

- name: Generate certificates
  become_user: "acme"
  become: true
  command: "acmetool want --batch {{acmetool_domains}}"
  register: result
  changed_when: "result.stdout"
